apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment1
spec:
  selector:
    matchLabels:
      app: assignment1
  replicas: 1
  template:
    metadata:
      labels:
        app: assignment1
    spec:
      containers:
      - name: assignment1
        image: assignment1
        ports:
        - containerPort: 80