apiVersion: v1
kind: Service
metadata:
  name: assignment1
  labels:
    app: assignment1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: assignment1
  type: LoadBalancer